In [0]:
import pandas as pd 
import numpy as np

In [0]:
df_bank = pd.read_csv('bank.csv')

In [234]:
df_bank.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [235]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [0]:
df_bank.drop(columns='RowNumber',axis=0,inplace=True)

In [237]:
print(any(df_bank['CustomerId'].duplicated()))  

False


In [0]:
df_bank.drop(columns='CustomerId',axis=0,inplace=True)

In [0]:
df_bank.drop(columns='Surname',axis=0,inplace=True)

In [240]:
df_bank.shape

(10000, 11)

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
labelgeog = LabelEncoder()

In [0]:
df_bank['Geography'] = labelgeog.fit_transform(df_bank['Geography'])

In [0]:
labelgen = LabelEncoder()

In [0]:
df_bank['Gender'] = labelgen.fit_transform(df_bank['Gender'])

In [246]:
pd.unique(df_bank['Gender'])

array([0, 1])

In [247]:
pd.unique(df_bank['Geography'])

array([0, 2, 1])

In [248]:
df_bank.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [0]:
X = df_bank.drop(columns='Exited',axis=0)

In [0]:
Y = df_bank['Exited']

In [251]:
print(X.shape)
print(Y.shape)

(10000, 10)
(10000,)


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3, random_state = 1)

In [254]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(7000, 10)
(7000,)
(3000, 10)
(3000,)


In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
Scale = StandardScaler()

In [257]:
X_train = Scale.fit_transform(X_train)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [258]:
X_test = Scale.transform(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [0]:
import keras
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import LeakyReLU

In [0]:
model = Sequential()

In [0]:
model.add(Dense(activation='relu',input_dim=10,units=6,kernel_initializer='uniform'))

In [0]:
model.add(Dense(activation='relu',units=6,kernel_initializer='uniform'))

In [0]:
model.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform'))

In [0]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [265]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
7000/7000 [==============================] - 1s 206us/step - loss: 0.5026 - acc: 0.7979
Epoch 2/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.4323 - acc: 0.7986
Epoch 3/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.4293 - acc: 0.7986
Epoch 4/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.4255 - acc: 0.7986
Epoch 5/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.4217 - acc: 0.8026
Epoch 6/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.4192 - acc: 0.8236
Epoch 7/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.4170 - acc: 0.8276
Epoch 8/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.4155 - acc: 0.8289
Epoch 9/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.4138 - acc: 0.8311
Epoch 10/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.4121 - acc: 0.8319

In [0]:
y_predict = model.predict(X_test)

In [0]:
final_prediction = y_predict > 0.5

In [268]:
print(final_prediction)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [0]:
conmat = confusion_matrix(y_test,final_prediction)

In [271]:
print(conmat)

[[2304   69]
 [ 434  193]]


In [0]:
acc = accuracy_score(y_test,final_prediction)

In [273]:
print(acc)

0.8323333333333334
